"use client";

import React, { useState } from "react";
import { FileText, Database, CheckCircle2, Copy, Check } from "lucide-react";

export default function TestArtifactViewer() {
  const [activeTab, setActiveTab] = useState<"test" | "mock" | "cli">("test");
  const [copied, setCopied] = useState(false);

  const testYaml = `# Generated by Keploy (3.8.57)
version: api.keploy.io/v1beta1
kind: Http
name: post-url-1
spec:
  metadata: {}
  req:
    method: POST
    proto_major: 1
    proto_minor: 1
    url: http://localhost:8080/url
    header:
      Content-Type: application/json
      Host: localhost:8080
      User-Agent: curl/8.5.0
    body: '{"url": "https://google.com"}'
    timestamp: 2026-10-03T12:21:20.351950925Z
  resp:
    status_code: 200
    header:
      Content-Type: application/json; charset=utf-8
      Date: Sat, 03 Oct 2026 12:21:20 GMT
    body: '{"ts":1791030080368551105,"url":"http://localhost:8080/Lhr4BWAi"}'
    status_message: OK
    timestamp: 2026-10-03T12:21:20.368936674Z
  assertions:
    noise:
      body.ts: []       # <-- Dynamic nanosecond timestamp automatically muted!
      header.Date: []   # <-- Dynamic HTTP date header muted to prevent flakiness
  created: 1791030080
  app_port: 8080`;

  const mockYaml = `# Intercepted MongoDB wire traffic generated by Keploy
version: api.keploy.io/v1beta1
kind: Mongo
name: mock-0
spec:
  metadata:
    connID: "0"
    operation: '{"flags":4,"collection_name":"admin.$cmd","query":{"isMaster":1}}'
    type: config
  requests:
    - header:
        length: 230
        Opcode: 2004
      message:
        collection_name: admin.$cmd
        query: '{"isMaster":1,"driver":{"name":"mongo-go-driver","version":"v1.8.1"}}'
  responses:
    - header:
        length: 329
        Opcode: 1
      message:
        documents:
          - '{"helloOk":true,"ismaster":true,"maxBsonObjectSize":16777216,"ok":1.0}'
---
version: api.keploy.io/v1beta1
kind: Mongo
name: mock-1
spec:
  metadata:
    collection_name: "keploy.url-shortener"
    type: query
  # Keploy stores the exact BSON documents returned by MongoDB during the curl call!`;

  const cliOutput = `keploy test -c "go run main.go handler.go" --delay 10

🐰 Starting Keploy Test Suite...
ℹ️ Intercepting outgoing TCP network calls via eBPF
ℹ️ Loaded 1 test suites from ./keploy directory

===============================================================
TEST RUN SUMMARY (test-set-5)
===============================================================
  ✔ [PASSED] post-url-1 (POST /url)
      Status: 200 OK (Expected 200 OK)
      Body Match: 100% [Dynamic noise: body.ts excluded]
      Mongo Mocks: 2/2 wire queries matched & served
  ✔ [PASSED] get-lhr4bwai-1 (GET /:param)
      Status: 307 Temporary Redirect
      Redirect Location: https://google.com

---------------------------------------------------------------
Total Tests: 2 | Passed: 2 | Failed: 0 | Execution Time: 1.42s
Result: SUCCESS (Zero Flakiness Detected)
===============================================================`;

  const currentContent =
    activeTab === "test" ? testYaml : activeTab === "mock" ? mockYaml : cliOutput;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(currentContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="my-8 rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-zinc-950 text-zinc-100 overflow-hidden shadow-lg">
      {/* Tab Navigation Header */}
      <div className="flex flex-wrap items-center justify-between px-4 py-3 bg-zinc-900 border-b border-zinc-800 gap-2">
        <div className="flex items-center gap-1.5">
          <button
            type="button"
            onClick={() => setActiveTab("test")}
            className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              activeTab === "test"
                ? "bg-zinc-800 text-orange-400 border border-zinc-700/80 shadow-xs"
                : "text-zinc-400 hover:text-zinc-200"
            }`}
          >
            <FileText className="w-3.5 h-3.5" />
            <span>test-set-5/tests/post-url-1.yaml</span>
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("mock")}
            className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              activeTab === "mock"
                ? "bg-zinc-800 text-purple-400 border border-zinc-700/80 shadow-xs"
                : "text-zinc-400 hover:text-zinc-200"
            }`}
          >
            <Database className="w-3.5 h-3.5" />
            <span>test-set-5/mocks.yaml</span>
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("cli")}
            className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              activeTab === "cli"
                ? "bg-zinc-800 text-emerald-400 border border-zinc-700/80 shadow-xs"
                : "text-zinc-400 hover:text-zinc-200"
            }`}
          >
            <CheckCircle2 className="w-3.5 h-3.5" />
            <span>Replay Test Report</span>
          </button>
        </div>

        <button
          type="button"
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-zinc-800 hover:bg-zinc-700 text-zinc-300 hover:text-white transition-colors text-xs font-medium"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-400" />
              <span className="text-emerald-400">Copied</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5 text-zinc-400" />
              <span>Copy</span>
            </>
          )}
        </button>
      </div>

      {/* Editor Content Area */}
      <div className="p-4 sm:p-5 overflow-x-auto text-xs sm:text-sm font-mono leading-relaxed bg-zinc-950 text-zinc-200">
        <pre className="!bg-transparent !p-0 !m-0 selection:bg-orange-500/30">
          <code>{currentContent}</code>
        </pre>
      </div>

      {/* Explanatory Footer Bar */}
      <div className="px-4 py-2.5 bg-zinc-900/80 border-t border-zinc-800/80 text-xs text-zinc-400 flex items-center justify-between">
        <span>
          {activeTab === "test" && "Notice the assertions.noise section muting dynamic body.ts values automatically."}
          {activeTab === "mock" && "Keploy captured raw MongoDB BSON wire protocol commands without any code mocks."}
          {activeTab === "cli" && "Recorded traffic replayed with 100% pass rate in under 1.5 seconds."}
        </span>
        <span className="text-[11px] font-mono text-zinc-500">Real Quickstart Fixture</span>
      </div>
    </div>
  );
}
